name: Desktop Build

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Get Latest Release
        id: release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          view_top: 1

      - name: Retrieve macOS Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE_CONVEYOR }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > macos.cer

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Cache Gradle and Build
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#            ${{ github.workspace }}/common/build
#            ${{ github.workspace }}/desktop/build
#            ~/Library/Caches/Hydraulic/Conveyor
#          key: ${{ runner.os }}-gradle-desktop
#          restore-keys: |
#            ${{ runner.os }}-gradle-desktop

      - name: Build with Gradle
        id: gradle-build
        run: |
          ./gradlew :desktop:build
          ./gradlew --stop

      
      - name: Upload Release Files
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: false
          omitBodyDuringUpdate: true
          tag: ${{ steps.release.outputs.tag_name }}
