name: Desktop Build

on:
  push:
    branches:
      - main  # Modify this to match your branch name
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Build with Gradle
        run: |
          ./gradlew :desktop:build
          ./gradlew --stop

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: desktop-build-artifact
          path: ./*  # Update this path to your actual build artifact location

