name: Desktop Build

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Get Latest Release
        id: release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          view_top: 1

      - name: Build with Gradle
        id: gradle-build
        run: |
          ./gradlew :desktop:build
          ./gradlew --stop

      - name: Create Release
        id: create-release
        run: |
          tag_name=$(git describe --tags --abbrev=0)  # Get the latest tag name
          echo "Creating release for tag: $tag_name"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"$tag_name\", \"name\": \"$tag_name\", \"body\": \"Release $tag_name\", \"draft\": false, \"prerelease\": false}" \
            "https://api.github.com/repos/${{ github.repository }}/releases"

      - name: Upload Release Files
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: false
          omitBodyDuringUpdate: true
          tag: ${{ github.ref }}

